@url = https://{{organization}}.visualstudio.com/_apis/wit

### Update fields on two different work items
PATCH {{url}}/$batch?api-version=4.1 HTTP/1.1
content-type: application/json
Authorization: Basic {{token}}

[{
	"method": "PATCH",
	"uri": "/_apis/wit/workitems/7023?api-version=4.1",
	"headers": {
		"Content-Type": "application/json-patch+json"     
	},
	"body": [{
		"op": "test",
		"path": "/rev",
		"value": 14
		},
		{
            "op": "replace",
            "path": "/fields/Microsoft.VSTS.Common.Priority",
            "value": 1
        },
        {
            "op": "replace",
            "path": "/fields/Microsoft.VSTS.Common.ValueArea",
            "value": "Architectural"
        },
		{
			"op": "add",
			"path": "/fields/System.History",
			"value": "Comments saved"
		}
	]
},
{
	"method": "PATCH",
	"uri": "/_apis/wit/workitems/6980?api-version=4.1",
	"headers": {
		"Content-Type": "application/json-patch+json"     
	},
	"body": [{
		"op": "test",
		"path": "/rev",
		"value": 21
		},
		{
            "op": "replace",
            "path": "/fields/Microsoft.VSTS.Common.Priority",
            "value": 1
        },
        {
            "op": "replace",
            "path": "/fields/Microsoft.VSTS.Common.ValueArea",
            "value": "Architectural"
        },
		{
			"op": "add",
			"path": "/fields/System.History",
			"value": "Comments saved"
		}
	]
}]